### ISSUE TITLE
Barplot for migration data

### ISSUE THREAD

**Issue by Augustin4762** [ikbentimkramer/cdphmd#101]
I intend to create a dropdown menu with 3 options as the provinces. Then for each province to present one barplot of the population change.( municipality on the x-axis, pop change on y).

**Comment by ikbentimkramer** [comment]
While making the bar plots for the subjective data, I found that putting the group labels on the y-axis made the graphs easier to read. When you have many labels on the x-axis, the label text starts overlapping and the bars (or in this case boxes) get really thin. Putting them on the y-axis, you don't have this problem. Also, you don't have to turn your head sideways to read the labels.

**Comment by Augustin4762** [comment]
True, I will change it then, thanks!

**Comment by Augustin4762** [comment]
The modules for the barplot were created. However, I face difficulties when choosing a province from the selection menu. I can't connect the barplots, which are 3 and saved in a list type to each of the province. Perhaps I might need a different drop_drown_menu function due to its structure. Please check on migration_map branch.

**Comment by ikbentimkramer** [comment]
This should be lowercase. Perhaps this fixes your issue
https://github.com/ikbentimkramer/cdphmd/blob/267164750d32a202408fb612aadc15431fa298eb/R/tab_migration_ui.R#L18
