### ISSUE TITLE
Add selection box for municipalities to linegraph housing stock

### ISSUE THREAD

**Issue by ikbentimkramer** [ikbentimkramer/cdphmd#24]
Right now the housing stock linegraph only shows data for the aggregate of Friesland, Groningen and Drenthe. It would be nice to be able to select different municipalities in the North of the Netherlands and have the linegraph show the housing stock for this municipality

**Comment by ikbentimkramer** [comment]
The codes for municipalities used by Statistics Netherlands can be found [here](https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/overig/gemeentelijke-indelingen-per-jaar).

**Comment by Augustin4762** [comment]
I got them in a different format: "PV20" , "PV21" , "PV22".
Just to be clear, what do we want to be able to select?
1) Provinces
2) Municipalities of these 3 provinces

**Comment by ikbentimkramer** [comment]
The second one. Municipalities.

Op wo 4 nov. 2020 20:46 schreef Augustin4762 <notifications@github.com>:

**Comment by Augustin4762** [comment]
Alright, that is going to be a little more work.
At this point, I am updating the data that should be uploaded and tailoring the clean function for the new dataset

**Comment by Augustin4762** [comment]
Also, since the municipalities vary across the 5 year period, shall we present data only on those that were present in all years/quarters?

**Comment by ikbentimkramer** [comment]
I think that makes sense for now. We might need to change it later
depending on what feedback we get. I'd say go for the option that is
easiest to implement for now

Op wo 4 nov. 2020 20:51 schreef Augustin4762 <notifications@github.com>:

**Comment by Augustin4762** [comment]
Some municipalities provide no data for the housing stock in certain years, there are 2 ways we can proceed with this:
1) Replace those values by an average value between known adjacent years
2)Compute those values from the monthly/quarterly reports, if available
3) Remove the municipality completely

**Comment by ikbentimkramer** [comment]
As an illustration to what I mean with the drop-down box, see [this page](https://shiny.rstudio.com/gallery/telephones-by-region.html). Instead of continents the selection box should contain municipalities and instead of a histogram it should be a lineplot.

**Comment by Augustin4762** [comment]
Shall we have in the sidebar only a tab called Housing stock, and in the body of the dashboard we can have the drop-down menu

**Comment by ikbentimkramer** [comment]
Implemented in dev
