### ISSUE TITLE
Add a plot depicting the balance of housing stock

### ISSUE THREAD

**Issue by Augustin4762** [ikbentimkramer/cdphmd#33]
Add a second graph, next to the initial housing stock, that shows the balance (change in comparison to the previous period).
A different plotting method might be more adequate to represent this indicator.

**Comment by Augustin4762** [comment]
Also, the stock balance is composed of residential and non-residential buildings, might be useful later on.

**Comment by ikbentimkramer** [comment]
Not necessarily. The column 'Purpose' in the housing stock dataset determines if you look at residential, non-residential or both.
