### ISSUE TITLE
Map data

### ISSUE THREAD

**Issue by Augustin4762** [ikbentimkramer/cdphmd#54]
Adding an interactive plot with map data, where you have initially selected the whole north area, then the 3 provinces, and then each municipality of the selected province

**Comment by ikbentimkramer** [comment]
Is this closed by #56?

**Comment by Augustin4762** [comment]
Right now, we have the map only at a municipality level, if we have time after the basics of the dashboard are done, I will continue working on the next 2 "levels"

**Comment by Augustin4762** [comment]
I will close it now, and open an updated issue if I ever start working on it
