### ISSUE TITLE
Include download page for report

### ISSUE THREAD

**Issue by ikbentimkramer** [ikbentimkramer/cdphmd#78]

**Comment by Augustin4762** [comment]
Shall we include more files available for download? For example the datasets from the get_data function, with the exception of the woononderzoek data. We can have a new item on the sidebar, which will give a drop down box with the selection options: final report, dataset1, datset2, etc, and when selected it will display (doc or table) a preview/header of the dataset or doc.

**Comment by ikbentimkramer** [comment]
It should be a page that hosts a markdown file, similar to the
accountability page. This markdown file can be found on the drive. Just a
link to the statically hosted report should suffice.

Op do 7 jan. 2021 16:03 schreef Augustin4762 <notifications@github.com>:
