### ISSUE TITLE
Data inconsistencies

### ISSUE THREAD

**Issue by Augustin4762** [ikbentimkramer/cdphmd#94]
The imputed data deviates from the data we get from CBS. 
For example the housing stock for Groningen in 2019 is 114733 according to the imputed data, and 129596 according to CBS 
I understand why there is this difference, however, it seems wrong to display such a different number in the dashboard when 
officially at that point there were 129596 houses registered in the municipality of Groningen.

**Comment by Augustin4762** [comment]
Given that we had no errors when displaying the maps for the price and stock, a solution would be to just use the CBS data for these 2 indicators. Though, it might be a problem for some of the line graphs.

**Comment by ikbentimkramer** [comment]
Can you check that the CBS housing data is residential housing only? I
recall that being a reason for the discrepancy.

**Comment by Augustin4762** [comment]
Just checked, you are right, 114733 represents only the buildings with "housing" function, and 129596 is the total buildings. I think it would be good to include this in the report, to specify what exactly are we showing.

**Comment by ikbentimkramer** [comment]
Closing this because this does not require further action regarding the dashboard
